#!/bin/bash
set -euo pipefail

AT_PORT="/dev/modem_at"
UPLINK_IFACE="${UPLINK_IFACE:-usb0}"
DNS_SERVERS="${DNS_SERVERS:-1.1.1.1 8.8.8.8}"
MAX_TRIES=15
COUNT=0

configure_dns() {
  if [ -z "$DNS_SERVERS" ]; then
    return
  fi
  if command -v resolvectl >/dev/null 2>&1; then
    resolvectl dns "$UPLINK_IFACE" $DNS_SERVERS || true
    resolvectl domain "$UPLINK_IFACE" "~." || true
  else
    {
      printf '# Generated by activate_4g.sh\n'
      for ns in $DNS_SERVERS; do
        printf 'nameserver %s\n' "$ns"
      done
    } > /etc/resolv.conf
  fi
}

while [ ! -e "$AT_PORT" ] && [ $COUNT -lt $MAX_TRIES ]; do
  sleep 2
  COUNT=$((COUNT + 1))
done

if [ -e "$AT_PORT" ]; then
  echo "4G modem $AT_PORT found. Activating PDP context."
  printf 'AT+CGACT=1,1\r' > "$AT_PORT"
  sleep 2
  echo "Updating DNS servers: $DNS_SERVERS"
  configure_dns
else
  echo "4G modem port $AT_PORT not found after multiple attempts. Check hardware."
  exit 1
fi